// auto-generated
// src/modules/audit/audit.constants.ts

export const AUDIT_ACTIONS = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  REGISTER: "REGISTER",

  PASSWORD_RESET_REQUEST: "PASSWORD_RESET_REQUEST",
  PASSWORD_RESET_SUCCESS: "PASSWORD_RESET_SUCCESS",

  EMAIL_VERIFIED: "EMAIL_VERIFIED",

  FAILED_LOGIN: "FAILED_LOGIN",
  ACCOUNT_LOCKED: "ACCOUNT_LOCKED",

  USER_UPDATED: "USER_UPDATED",
  USER_DELETED: "USER_DELETED",
};